---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ansible-tower
  namespace: tower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-tower
        version: v1
    spec:
      containers:
      - name: tower
        image: dynatraceacm/ansibletower:3.3.1-1-2
        livenessProbe:
          httpGet:
            path: /api/v1/ping/
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ping/
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10