---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ticketmonster-backend-v2
  namespace: ticketmonster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ticketmonster-backend-v2
        version: v1
    spec:
      containers:
      - name: ticketmonster-backend-v2
        image: dynatraceacm/ticketmonster-backend-v2:latest
        env:
        - name: MYSQL_SERVICE_HOST
          value: ticketmonster-db
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 400m
            memory: 768Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ff4j-console
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /ff4j-console
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 15
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: ticketmonster-backend-v2
  labels:
    app: ticketmonster-backend-v2
  namespace: ticketmonster
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ticketmonster-backend-v2
  type: LoadBalancer
---